spring:
  application:
    name: research
  webflux:
    base-path: /research
  data:
    mongodb:
      uri: mongodb://localhost:27017/literature
  ai:
    openai:
      api-key: {OPENAI_API_KEY}
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
    basePath: /api
