spring:
  application:
    name: research
  webflux:
    base-path: /research
springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
    enabled: true
  api-docs:
    enabled: true
    basePath: /api
